DirectoryPath: _site
CheckDoctype: false
IgnoreURLs:
- "history.newtheatre.org.uk"
- "photos.smugmug.com"
- "photos.newtheatre.org.uk"
- "archive.is"
- "castingcallpro.com"
- "stagejobspro.com"
IgnoreDirs:
- "^lib"

