DirectoryPath: _site
CheckDoctype: false
IgnoreURLs:
- "history.newtheatre.org.uk"
- "photos.smugmug.com"
- "photos.newtheatre.org.uk"
- "archive.is"
- "castingcallpro.com"
- "stagejobspro.com"
- "soundcloud.com"
- "impactnottingham.com"
- "http://www.su-web2.nottingham.ac.uk/"
- "http://young-perspective.net/"
- "https://web.archive.org"
- "http://philgeller.co.uk/"
IgnoreDirs:
- "^lib"

