version: '3'

services:
  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: _docker/app.dockerfile
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
    networks:
      - website-network
    entrypoint: tail -f /dev/null
    environment:
      EXECJS_RUNTIME: Disabled

networks:
  website-network:
    driver: bridge


