source 'https://rubygems.org'

gem 'sass'
gem 'jekyll', '~>3.3.0'
gem 'jekyll-sitemap', '~>0.12.0'
gem 'jekyll-redirect-from', '~>0.11.0'
gem 'git'
gem 'httparty', '~>0.14.0'
gem 'liquid-c'
gem 'octokit', '~>4.3'
