source 'https://rubygems.org'

gem 'jekyll', '~>3.5.2'
gem 'jekyll-sitemap', '~>1.1.0'
gem 'jekyll-redirect-from', '~>0.12.1'
gem 'git'
gem 'httparty', '~>0.15.6'
gem 'liquid-c'
gem 'octokit', '~>4.7.0'
gem 'i18n'
