#!/usr/bin/env sh

docker-compose down -v
docker-compose build --no-cache
docker-compose up -d --remove-orphans
docker-compose exec --no-tty app bundle install
docker-compose exec --no-tty app npm install
docker-compose exec --no-tty app npm run bower:install
docker-compose exec --no-tty app npm run gulp:build
