import os

years = range(1940, 2015)

def make_template(year, year_range, year_range_short, year_range_short_pretty):
    return """---
layout: show_year
group: show_year
sort: """ + year + """
title: """ + year_range + """
year: \"""" + year_range_short + """\"
decade: \"""" + year[:3] + """\"
message: The pages in this directory are automatically generated by the year_generator.py script. DO NOT manually edit them, your changes will be overwritten the next time the script runs.
---

{% assign shows = site.collections.shows.docs | where:"year", \"""" + year_range_short + """\" %}

{% include show_list.html %}

"""

for year in years:
  year_this = str(year) # 2012
  year_next = str(year+1) # 2013

  year_range = "{} - {}".format(year_this, year_next[2:]) # 2012 - 13
  year_range_short = "{}_{}".format(year_this[2:], year_next[2:])
  year_range_short_pretty = "{}-{}".format(year_this[2:], year_next[2:])
  content = make_template(str(year), year_range, year_range_short, year_range_short_pretty)
  filename = "shows/{}.html".format(year_range_short)
  stream = open(filename, "w")
  stream.write(content)
  stream.close()
